dist: trusty

language: python

addons:
    apt:
        packages:
            - gcc-4.8
            - g++-4.8

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

install:
    - source .ci/travis.sh

script:
    - py.test -v

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then source .ci/build-docs.sh; fi
